default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: om30_development

test:
  <<: *default
  database: om30_test

production:
  <<: *default
  database: om30_production
  username: om30
  password: <%= ENV["OM30_DATABASE_PASSWORD"] %>
